# Automatically generated by SST
# pylint: disable=all
# ruff: noqa
from typing import Any

class Resource:
    class Api:
        type: str
        url: str
    class App:
        name: str
        stage: str
    class Company:
        type: str
        url: str
    class JwtSecret:
        type: str
        value: str
    class Marketing:
        type: str
        url: str
    class MongodbUri:
        type: str
        value: str
    class PhotosBucket:
        name: str
        type: str
    class SesFromEmail:
        type: str
        value: str
    class SmsDeliveryTopic:
        arn: str
        type: str
    class SmsInboundTopic:
        arn: str
        type: str
    class SmsPoolId:
        type: str
        value: str
    class StripePriceLift79:
        type: str
        value: str
    class StripePublishableKey:
        type: str
        value: str
    class StripeSecretKey:
        type: str
        value: str
    class StripeWebhookSecret:
        type: str
        value: str
    class Web:
        type: str
        url: str

